config/routes.rb
Rails.application.routes.draw do
  get 'comments/new'
  get 'users/index'
  get 'users/show'
  get 'comments/edit'
  root 'blogs#index'
  
  devise_for :users
  get '/users/:id', to: 'users#show'


  resources :blogs do
    resources :comments
  end
    
end
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ActiveRecord::Base
    belongs_to :user
    has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :blog
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
    # before any blog action happens, it will authenticate the user
    before_action :authenticate_user!
    def index
      @user = current_user.email
      @blogs = Blog.all
    end
    #Other Restful methods show, new, edit, create, update, destroy
     
      # GET /posts/1
      def show
        @blog = Blog.find(params[:id])
      end
    
      # GET /posts/new
      def new
        @blog = Blog.new
      end
    
      # GET /posts/1/edit
      def edit
        @blog = Blog.find(params[:id])
      end
    
      # POST /posts
      def create
        @blog = Blog.new(blog_params)
        @blog.user_id = current_user.id
        if @blog.save
          redirect_to "/"
        else
          render "/blogs/new"
        end
      end
    
      # PATCH/PUT /posts/1
      def update
        @blog = Blog.find(params[:id])
        @blog.update(blog_params)
        if @blog.save
          redirect_to "/"
        else
          render "/blogs/new"
        end
      end
    
      # DELETE /posts/1
      def destroy
        @blog = Blog.find(params[:id])
        @blog.destroy
        redirect_to "/"
      end
    
      private
        # Only allow white list through, never trust parameters from the internet.
        def blog_params
          params.require(:blog).permit(:title, :body, :user_id)
        end
    end
  

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  # before any blog action happens, it will authenticate the user
  before_action :authenticate_user!
  def index
    @user = current_user.email
    @comments = Comment.all
  end
  #Other Restful methods show, new, edit, create, update, destroy
   
    # GET /posts/1
    def show
      @comment = Comment.find(params[:id])
    end
  
    # GET /posts/new
    def new
      @comment = Comment.new
    end
  
    # GET /posts/1/edit
    def edit
      @comment = Comment.find(params[:id])
    end
  
    # POST /posts
    def create
      @blog = Blog.find(params[:blog_id])
      @comment = current_user.comments.new(comment_params)
      @comment.blog = @blog
      if @comment.save
        redirect_to "/"
      else
        render "/blogs/new"
      end
    end
  
    # PATCH/PUT /posts/1
    def update
      @comment = Comment.find(params[:id])
      @comment.update(comment_params)
      if @comment.save
        redirect_to "/"
      else
        render "/blogs/new"
      end
    end
  
    # DELETE /posts/1
    def destroy
      @comment = Comment.find(params[:id])
      @comment.destroy
      redirect_to "/"
    end
  
    private
      # Only allow white list through, never trust parameters from the internet.
      def comment_params
        params.require(:comment).permit(:content, :user_id, :blog_id)
      end
  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/blogs/edit.html.erb
<h1> Edit Post<%=@blog.id%></h1>

<%= form_for @blog do |f| %>

Title:<%= f.text_field :title %><br>
Content: <%= f.text_field :body %><br>


<%= f.submit "Update Post" %>
<% end %>

app/views/blogs/index.html.erb
<h1>Welcome !</h1>
<p><%= @user %></p>
<% @blogs.each do |p| %>

<div class="posts">
 <div>What would you like to say to the world? 
 

 <%= button_to "Delete Post", blog_path(p.id), method: :delete, data: {confirm: "Delete Post?"}%>
 <a href="/blogs/<%=p.id%>/edit"><b>Edit Post</b></a><br>
 <b><%= p.title %></b><br>
 <%= p.body %></div><br><br>

 <a href="/blogs/<%=p.id%>"><b>Comment</b></a><br>
 
 <% end %>

app/views/blogs/new.html.erb
<%= form_for @blog do |f| %>

Title:<%= f.text_field :title %><br>
Content: <%= f.text_area :body %><br>

<%= f.submit "Create Post" %>
<% end %>

app/views/blogs/show.html.erb
<h2><%= @blog.title %></h2>

<p><%= @blog.body %></p><br>

<h4>Comments</h4>

<% @blog.comments.each do |c|%>
    <%= c.content %><br>
<%end%>

<% if user_signed_in? %>
    <%= form_for([@blog, @blog.comments.build]) do |f| %>
        <%= f.text_field :content %><br />
        <%= f.submit "Comment" %>
    <% end %>
<% end %>

app/views/comments/edit.html.erb
<h1> Edit Comment<%=@blog.id%></h1>

<%= form_for @blog do |f| %>

Title:<%= f.text_field :title %><br>
Content: <%= f.text_field :body %><br>


<%= f.submit "Update Comment" %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav nav-tabs">
  <li><%= link_to 'Home', root_path%></li>

  <% if user_signed_in? %>
  <li><%= link_to "Create A Post", new_blog_path, :method => "get" %></li>
 <li><a href="/signout/">Sign Out</a></li>
  <% end %>

</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MicroBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %> 
    


<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Home Page</h1>